---
abstract: 'IUP bindings to Perl'
author:
  - 'KMX <kmx@cpan.org>'
build_requires:
  Alien::IUP: 0.304
  Carp: 0
  ExtUtils::CBuilder: 0
  Module::Build: 0.36
  Test::More: 0
  constant: 0
  perl: 5.008008
configure_requires:
  Alien::IUP: 0.304
  Module::Build: 0.36
  perl: 5.008008
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
keywords:
  - IUP
  - portable
  - toolkit
  - graphical
  - user
  - interfaces
  - tecgraf
  - cross-platform
  - GUI
  - Windows
  - GTK
  - Motif
  - X11
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IUP
provides:
  IUP:
    file: lib/IUP.pm
    version: 0.005_2
  IUP::Button:
    file: lib/IUP/Button.pm
    version: 0
  IUP::Canvas:
    file: lib/IUP/Canvas.pm
    version: 0
  IUP::Canvas::Bitmap:
    file: lib/IUP/Canvas.pm
    version: 0
  IUP::Canvas::FileBitmap:
    file: lib/IUP/Canvas/FileBitmap.pm
    version: 0
  IUP::Canvas::FileVector:
    file: lib/IUP/Canvas/FileVector.pm
    version: 0
  IUP::Canvas::Palette:
    file: lib/IUP/Canvas.pm
    version: 0
  IUP::Canvas::Pattern:
    file: lib/IUP/Canvas.pm
    version: 0
  IUP::Canvas::Stipple:
    file: lib/IUP/Canvas.pm
    version: 0
  IUP::CanvasGL:
    file: lib/IUP/CanvasGL.pm
    version: 0
  IUP::Cbox:
    file: lib/IUP/Cbox.pm
    version: 0
  IUP::Cells:
    file: lib/IUP/Cells.pm
    version: 0
  IUP::Clipboard:
    file: lib/IUP/Clipboard.pm
    version: 0
  IUP::ColorBar:
    file: lib/IUP/ColorBar.pm
    version: 0
  IUP::ColorBrowser:
    file: lib/IUP/ColorBrowser.pm
    version: 0
  IUP::ColorDlg:
    file: lib/IUP/ColorDlg.pm
    version: 0
  IUP::Constants:
    file: lib/IUP/Constants.pm
    version: 0
  IUP::Dial:
    file: lib/IUP/Dial.pm
    version: 0
  IUP::Dialog:
    file: lib/IUP/Dialog.pm
    version: 0
  IUP::ElementPropertiesDialog:
    file: lib/IUP/ElementPropertiesDialog.pm
    version: 0
  IUP::FileDlg:
    file: lib/IUP/FileDlg.pm
    version: 0
  IUP::Fill:
    file: lib/IUP/Fill.pm
    version: 0
  IUP::FontDlg:
    file: lib/IUP/FontDlg.pm
    version: 0
  IUP::Frame:
    file: lib/IUP/Frame.pm
    version: 0
  IUP::Hbox:
    file: lib/IUP/Hbox.pm
    version: 0
  IUP::Image:
    file: lib/IUP/Image.pm
    version: 0
  IUP::Internal::Callback:
    file: lib/IUP/Internal/Callback.pm
    version: 0
  IUP::Internal::Canvas:
    file: lib/IUP/Internal/Canvas.pm
    version: 0
  IUP::Internal::Element:
    file: lib/IUP/Internal/Element.pm
    version: 0
  IUP::Internal::LibraryIup:
    file: lib/IUP/Internal/LibraryIup.pm
    version: 0
  IUP::Item:
    file: lib/IUP/Item.pm
    version: 0
  IUP::Label:
    file: lib/IUP/Label.pm
    version: 0
  IUP::LayoutDialog:
    file: lib/IUP/LayoutDialog.pm
    version: 0
  IUP::List:
    file: lib/IUP/List.pm
    version: 0
  IUP::Matrix:
    file: lib/IUP/Matrix.pm
    version: 0
  IUP::Menu:
    file: lib/IUP/Menu.pm
    version: 0
  IUP::MessageDlg:
    file: lib/IUP/MessageDlg.pm
    version: 0
  IUP::Normalizer:
    file: lib/IUP/Normalizer.pm
    version: 0
  IUP::PPlot:
    file: lib/IUP/PPlot.pm
    version: 0
  IUP::ProgressBar:
    file: lib/IUP/ProgressBar.pm
    version: 0
  IUP::Radio:
    file: lib/IUP/Radio.pm
    version: 0
  IUP::Sbox:
    file: lib/IUP/Sbox.pm
    version: 0
  IUP::Separator:
    file: lib/IUP/Separator.pm
    version: 0
  IUP::Spin:
    file: lib/IUP/Spin.pm
    version: 0
  IUP::SpinBox:
    file: lib/IUP/SpinBox.pm
    version: 0
  IUP::Split:
    file: lib/IUP/Split.pm
    version: 0
  IUP::Submenu:
    file: lib/IUP/Submenu.pm
    version: 0
  IUP::Tabs:
    file: lib/IUP/Tabs.pm
    version: 0
  IUP::Text:
    file: lib/IUP/Text.pm
    version: 0
  IUP::Timer:
    file: lib/IUP/Timer.pm
    version: 0
  IUP::Toggle:
    file: lib/IUP/Toggle.pm
    version: 0
  IUP::Tree:
    file: lib/IUP/Tree.pm
    version: 0
  IUP::User:
    file: lib/IUP/User.pm
    version: 0
  IUP::Val:
    file: lib/IUP/Val.pm
    version: 0
  IUP::Vbox:
    file: lib/IUP/Vbox.pm
    version: 0
  IUP::Zbox:
    file: lib/IUP/Zbox.pm
    version: 0
requires:
  Carp: 0
  constant: 0
  perl: 5.008008
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=IUP
  license: http://www.opensource.org/licenses/mit-license.php
  repository: https://github.com/kmx/perl-iup
version: 0.005_2
